### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by michael6030** [ttoff/dpdk#5]
Using Panda3D installation located at C:\Users\Michael\Desktop\Panda3D-1.10.13-x64
Requirement already satisfied: aiohttp in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from -r requirements.txt (line 1)) (3.8.4)
Requirement already satisfied: toml in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from -r requirements.txt (line 2)) (0.10.2)
Collecting wxpython
  Using cached wxPython-4.2.1.tar.gz (73.7 MB)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: asynctest==0.13.0; python_version < "3.8" in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (0.13.0)
Requirement already satisfied: typing-extensions>=3.7.4; python_version < "3.8" in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (4.7.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (1.3.3)
Requirement already satisfied: attrs>=17.3.0 in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: pillow in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from wxpython->-r requirements.txt (line 3)) (9.5.0)
Requirement already satisfied: six in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from wxpython->-r requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: numpy in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from wxpython->-r requirements.txt (line 3)) (1.21.6)
Requirement already satisfied: idna>=2.0 in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from attrs>=17.3.0->aiohttp->-r requirements.txt (line 1)) (6.7.0)
Requirement already satisfied: zipp>=0.5 in c:\users\michael\desktop\panda3d-1.10.13-x64\python\lib\site-packages (from importlib-metadata; python_version < "3.8"->attrs>=17.3.0->aiohttp->-r requirements.txt (line 1)) (3.15.0)
Using legacy setup.py install for wxpython, since package 'wheel' is not installed.
Installing collected packages: wxpython
    Running setup.py install for wxpython ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Michael\Desktop\Panda3D-1.10.13-x64\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Michael\\AppData\\Local\\Temp\\pip-install-3bw3mxdo\\wxpython\\setup.py'"'"'; __file__='"'"'C:\\Users\\Michael\\AppData\\Local\\Temp\\pip-install-3bw3mxdo\\wxpython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Michael\AppData\Local\Temp\pip-record-lwml_jbd\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Michael\Desktop\Panda3D-1.10.13-x64\python\Include\wxpython'
         cwd: C:\Users\Michael\AppData\Local\Temp\pip-install-3bw3mxdo\wxpython\
    Complete output (33 lines):
    running install
    running build
    Will build using: "C:\Users\Michael\Desktop\Panda3D-1.10.13-x64\python\python.exe"
    3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
    Python's architecture is 64bit
    cfg.VERSION: 4.2.1

    Running command: build
    Running command: build_wx
    Traceback (most recent call last):
      File "build.py", line 2377, in <module>
        main(sys.argv[1:])
      File "build.py", line 208, in main
        function(options, args)
      File "build.py", line 1452, in cmd_build
        cmd_build_wx(options, args)
      File "build.py", line 1462, in cmd_build_wx
        checkCompiler()
      File "build.py", line 795, in checkCompiler
        info = getMSVCInfo(PYTHON, arch, set_env=True)
      File "C:\Users\Michael\AppData\Local\Temp\pip-install-3bw3mxdo\wxpython\buildtools\config.py", line 993, in getMSVCInfo
        from attrdict import AttrDict
    ModuleNotFoundError: No module named 'attrdict'
    Finished command: build_wx (0.4s)
    Finished command: build (0.4s)
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.

    **"C:\Users\Michael\Desktop\Panda3D-1.10.13-x64\python\python.exe" -u build.py build
    Command '"C:\Users\Michael\Desktop\Panda3D-1.10.13-x64\python\python.exe" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Michael\Desktop\Panda3D-1.10.13-x64\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Michael\\AppData\\Local\\Temp\\pip-install-3bw3mxdo\\wxpython\\setup.py'"'"'; __file__='"'"'C:\\Users\\Michael\\AppData\\Local\\Temp\\pip-install-3bw3mxdo\\wxpython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Michael\AppData\Local\Temp\pip-record-lwml_jbd\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Michael\Desktop\Panda3D-1.10.13-x64\python\Include\wxpython' Check the logs for full command output.**
**_WARNING: You are using pip version 20.1.1; however, version 23.1.2 is available.
You should consider upgrading via the 'C:\Users\Michael\Desktop\Panda3D-1.10.13-x64\python\python.exe -m pip install --upgrade pip' command._**
Traceback (most recent call last):
  File "C:\Users\Michael\Desktop\Panda3D-1.10.13-x64\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Michael\Desktop\Panda3D-1.10.13-x64\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Michael\Desktop\dpdk-master\dpdk-master\src\base\DPDKBase.py", line 9, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
Press any key to continue . . .

**Comment by michael6030** [comment]
This was done with a clean, full install of panda 3d 1.10.3
