### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by michael6030** [ttoff/dpdk#6]
Using Panda3D installation located at C:/Panda3D-1.10.13-x64
Requirement already satisfied: aiohttp in c:\panda3d-1.10.13-x64\python\lib\site-packages (from -r requirements.txt (line 1)) (3.8.4)
Requirement already satisfied: toml in c:\panda3d-1.10.13-x64\python\lib\site-packages (from -r requirements.txt (line 2)) (0.10.2)
Requirement already satisfied: wxpython in c:\panda3d-1.10.13-x64\python\lib\site-packages (from -r requirements.txt (line 3)) (4.2.1)
Requirement already satisfied: attrs>=17.3.0 in c:\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\panda3d-1.10.13-x64\python\lib\site-packages (from aiohttp->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: pillow in c:\panda3d-1.10.13-x64\python\lib\site-packages (from wxpython->-r requirements.txt (line 3)) (10.0.0)
Requirement already satisfied: six in c:\panda3d-1.10.13-x64\python\lib\site-packages (from wxpython->-r requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: numpy in c:\panda3d-1.10.13-x64\python\lib\site-packages (from wxpython->-r requirements.txt (line 3)) (1.25.1)
Requirement already satisfied: idna>=2.0 in c:\panda3d-1.10.13-x64\python\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->-r requirements.txt (line 1)) (3.4)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Michael\Desktop\dpdk-master (2)\dpdk-master\src\base\DPDKBase.py", line 17, in <module>
    from src.base import DPDKGlobal
  File "C:\Users\Michael\Desktop\dpdk-master (2)\dpdk-master\src\base\DPDKGlobal.py", line 1, in <module>
    from src.base.DPDKBase import DPDKBase
  File "C:\Users\Michael\Desktop\dpdk-master (2)\dpdk-master\src\base\DPDKBase.py", line 18, in <module>
    from src.ott.Settings import Settings
  File "C:\Users\Michael\Desktop\dpdk-master (2)\dpdk-master\src\ott\Settings.py", line 11, in <module>
    class Settings(collections.MutableMapping):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'
Press any key to continue . . .

**Comment by michael6030** [comment]
this is my latest log after upgrading pip.  Building wheel for wxpython (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for wxpython (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      running bdist_wheel
      running build
      Will build using: "C:\Panda3D-1.10.13-x64\python\ppython.exe"
      3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
      Python's architecture is 64bit
      cfg.VERSION: 4.2.1

      Running command: build
      Running command: build_wx
      Traceback (most recent call last):
        File "build.py", line 2377, in <module>
          main(sys.argv[1:])
        File "build.py", line 208, in main
          function(options, args)
        File "build.py", line 1452, in cmd_build
          cmd_build_wx(options, args)
        File "build.py", line 1462, in cmd_build_wx
          checkCompiler()
        File "build.py", line 795, in checkCompiler
          info = getMSVCInfo(PYTHON, arch, set_env=True)
        File "C:\Users\Michael\AppData\Local\Temp\pip-install-4h1koyjw\wxpython_b4f2987139124fbc9dcda8799244239d\buildtools\config.py", line 993, in getMSVCInfo
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      Finished command: build_wx (0.6s)
      Finished command: build (0.6s)
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "C:\Panda3D-1.10.13-x64\python\ppython.exe" -u build.py build
      Command '"C:\Panda3D-1.10.13-x64\python\ppython.exe" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxpython
Failed to build wxpython
ERROR: Could not build wheels for wxpython, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "C:\Panda3D-1.10.13-x64\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Panda3D-1.10.13-x64\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Panda3D-1.10.13-x64\dpdk-master\src\base\DPDKBase.py", line 9, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
Press any key to continue . . .
